ValueSet: VsMinisteroSaluteIdAziendeOspedaliere
Id: minsan-idAziendeOspedaliere
Title: "Ministero della Salute - ID Aziende Ospedaliere"
Description: "Ministero della Salute - Aziende Ospedaliere (HSP11)"
* ^experimental = false
//----------------------------------------
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#010906 "AZ. OSPEDAL. S. CROCE E CARLE"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#010907 "AZ. SS.ANTONIO E BIAGIO E C.ARRIGO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#010908 "OSPEDALE MAURIZIANO UMBERTO I - TORINO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030701 "ASST GRANDE OSPEDALE METROPOLITANO NIGUA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030702 "ASST SANTI PAOLO E CARLO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030703 "ASST FATEBENEFRATELLI SACCO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030704 "ASST SPEC.ORT.TRAUMATOLOGICO G.PINI/CTO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030705 "ASST OVEST MILANESE"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030706 "ASST RHODENSE"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030707 "ASST NORD MILANO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030708 "ASST MELEGNANO E DELLA MARTESANA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030709 "ASST DI LODI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030710 "ASST DEI SETTE LAGHI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030711 "ASST DELLA VALLE OLONA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030712 "ASST LARIANA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030713 "ASST DELLA VALTELLINA E DELL'ALTO LARIO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030714 "ASST DELLA VALCAMONICA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030715 "ASST DI LECCO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030717 "ASST DELLA BRIANZA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030718 "ASST PAPA GIOVANNI XXIII"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030719 "ASST DI BERGAMO OVEST"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030720 "ASST DI BERGAMO EST"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030721 "ASST DEGLI SPEDALI CIVILI DI BRESCIA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030722 "ASST DELLA FRANCIACORTA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030723 "ASST DEL GARDA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030724 "ASST DI CREMONA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030725 "ASST DI MANTOVA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030726 "ASST DI CREMA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#030727 "ASST DI PAVIA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#050901 "AZIENDA OSPEDALE - UNIVERSITA' PADOVA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#100901 "AZIENDA OSPEDALIERA DI PERUGIA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#100902 "AZIENDA OSPEDALIERA 'S. MARIA' - TERNI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#110905 "AZIENDA OSP. UNIVERSITARIA DELLE MARCHE"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#120901 "AZ.OSP.SAN CAMILLO-FORLANINI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#120902 "AZIENDA OSP. S.GIOVANNI/ADDOLORATA ROMA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150901 "AZIENDA OSPEDALIERA 'A. CARDARELLI'"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150902 "A.O.R.N. SANTOBONO-PAUSILIPON"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150903 "Azienda Ospedaliera dei Colli"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150905 "AZIENDA OSPEDALIERA S. G. MOSCATI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150906 "AZIENDA OSPEDALE `AO SAN PIO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#150907 "A.O. SANT'ANNA E SAN SEBASTIANO CASERTA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#170901 "AZIENDA OSPEDALIERA REGIONALE 'S. CARLO'"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#180912 "AZIENDA OSPEDALIERA DI COSENZA"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#180913 "Azienda Ospedaliera Pugliese - Ciaccio"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#180914 "A.O.U. MATER DOMINI CATANZARO"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#180915 "Azienda Osped. Bianchi Melacrino Morelli"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190921 "A.O. per l'Emergenza Cannizzaro"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190922 "ARNAS GARIBALDI"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190924 "Azienda Ospedaliera Papardo"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190926 "A.O.R Villa Sofia Cervello"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#190927 "Azienda Ospedaliera 'Civico-Di Cristina-"
* http://hl7.it/fhir/televisita/CodeSystem/minsan-hsp#200904 "AZIENDA OSPEDALIERA G.BROTZU"

